include pyflakes in githook

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -6,6 +6,13 @@ if [[ $? != 0 ]]; then
     exit 1
 fi
 
+pyflakes $(fd -e py)
+
+if [[ $? != 0 ]]; then
+    echo "There are pyflakes errors, fix them before committing"
+    exit 1
+fi
+
 black --check $(fd -e py)
 if [[ $? != 0 ]]; then
     echo "There are formatting errors, run black"
