add tests to proper file structure so they run with python -m unittest discover

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+python -m unittest discover
+if [[ $? != 0 ]]; then
+    echo "There are failing tests, fix?"
+    exit 1
+fi
+
 mypy --ignore-missing-imports $(fd -e py)
 if [[ $? != 0 ]]; then
     echo "There are mypy errors, fix them before committing"
