sort githooks

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,11 +1,5 @@
 #!/bin/bash
 
-python -m unittest discover
-if [[ $? != 0 ]]; then
-    echo "There are failing tests, fix?"
-    exit 1
-fi
-
 mypy --ignore-missing-imports $(fd -e py)
 if [[ $? != 0 ]]; then
     echo "There are mypy errors, fix them before committing"
@@ -22,6 +16,12 @@ fi
 black --check $(fd -e py)
 if [[ $? != 0 ]]; then
     echo "There are formatting errors, run black"
+    exit 1
+fi
+
+python -m unittest discover
+if [[ $? != 0 ]]; then
+    echo "There are failing tests, fix?"
     exit 1
 fi
 
